version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run streamlit_app.py --server.port=9998 --server.address=0.0.0.0 --server.headless=true
    ports:
      - "9998:9998"
    env_file:
      - .env
    restart: on-failure

